language: go

go:
    - 1.13
    - tip

services:
    - docker

jobs:
    include:
        - stage: build
        script: make build-device
        - stage: deploy
        script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - make make docker
