language: go

go:
    - 1.13
    - tip

services:
    - docker

script:
    - make build-device

deploy:
    provider: script
    script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make make docker
