apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  data_source.yml: |
    # config file version
    apiVersion: 1
    datasources:
    - name: Palinta
      type: influxdb
      # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
      access: proxy
      # <string> url
      url: http://influxdb:8086
      # <string> database password, if used
      secureJsonData:
        password: root
      # <string> database user, if used
      user: root
      # <string> database name, if used
      database: demeter
      # version
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: false
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: "/etc/grafana/provisioning/dashboards"
  dashboard.json: |
    {
        "annotations": {
        "list": [
            {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
            }
        ]
        },
        "editable": true,
        "gnetId": null,
        "graphTooltip": 0,
        "id": 2,
        "links": [],
        "panels": [
        {
            "datasource": "Palinta",
            "fieldConfig": {
            "defaults": {
                "custom": {},
                "mappings": [],
                "thresholds": {
                "mode": "absolute",
                "steps": [
                    {
                    "color": "dark-purple",
                    "value": null
                    },
                    {
                    "color": "red",
                    "value": 80
                    }
                ]
                }
            },
            "overrides": []
            },
            "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
            },
            "id": 4,
            "options": {
            "orientation": "auto",
            "reduceOptions": {
                "calcs": [
                "last"
                ],
                "fields": "",
                "values": false
            },
            "showThresholdLabels": false,
            "showThresholdMarkers": true
            },
            "pluginVersion": "7.1.0",
            "targets": [
            {
                "groupBy": [
                {
                    "params": [
                    "$__interval"
                    ],
                    "type": "time"
                },
                {
                    "params": [
                    "null"
                    ],
                    "type": "fill"
                }
                ],
                "measurement": "temp",
                "orderByTime": "ASC",
                "policy": "default",
                "refId": "A",
                "resultFormat": "time_series",
                "select": [
                [
                    {
                    "params": [
                        "data"
                    ],
                    "type": "field"
                    },
                    {
                    "params": [],
                    "type": "mean"
                    }
                ]
                ],
                "tags": []
            }
            ],
            "timeFrom": null,
            "timeShift": null,
            "title": "Fancy panel",
            "type": "gauge"
        },
        {
            "datasource": null,
            "fieldConfig": {
            "defaults": {
                "custom": {},
                "mappings": [],
                "thresholds": {
                "mode": "absolute",
                "steps": [
                    {
                    "color": "green",
                    "value": null
                    },
                    {
                    "color": "red",
                    "value": 80
                    }
                ]
                }
            },
            "overrides": []
            },
            "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
            },
            "id": 6,
            "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
                "calcs": [
                "mean"
                ],
                "fields": "",
                "values": false
            },
            "textMode": "auto"
            },
            "pluginVersion": "7.1.0",
            "timeFrom": null,
            "timeShift": null,
            "title": "Random Panel",
            "type": "stat"
        },
        {
            "aliasColors": {},
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": "Palinta",
            "fieldConfig": {
            "defaults": {
                "custom": {}
            },
            "overrides": []
            },
            "fill": 1,
            "fillGradient": 0,
            "gridPos": {
            "h": 14,
            "w": 24,
            "x": 0,
            "y": 8
            },
            "hiddenSeries": false,
            "id": 2,
            "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
            },
            "lines": true,
            "linewidth": 1,
            "nullPointMode": "null",
            "percentage": false,
            "pluginVersion": "7.1.0",
            "pointradius": 2,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": false,
            "targets": [
            {
                "groupBy": [
                {
                    "params": [
                    "$__interval"
                    ],
                    "type": "time"
                },
                {
                    "params": [
                    "null"
                    ],
                    "type": "fill"
                }
                ],
                "measurement": "temp",
                "orderByTime": "ASC",
                "policy": "default",
                "refId": "A",
                "resultFormat": "time_series",
                "select": [
                [
                    {
                    "params": [
                        "data"
                    ],
                    "type": "field"
                    },
                    {
                    "params": [],
                    "type": "mean"
                    }
                ]
                ],
                "tags": []
            }
            ],
            "thresholds": [],
            "timeFrom": null,
            "timeRegions": [],
            "timeShift": null,
            "title": "Demeter",
            "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
            },
            "type": "graph",
            "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
            },
            "yaxes": [
            {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
            },
            {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
            }
            ],
            "yaxis": {
            "align": false,
            "alignLevel": null
            }
        }
        ],
        "refresh": "10s",
        "schemaVersion": 26,
        "style": "dark",
        "tags": [],
        "templating": {
        "list": []
        },
        "time": {
        "from": "now-1h",
        "to": "now"
        },
        "timepicker": {
        "refresh_intervals": [
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
        ]
        },
        "timezone": "",
        "title": "Palinta - default",
        "uid": "jk29mq7Gk",
        "version": 2
    }